version: 2
updates:
  - package-ecosystem: "dotnet"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        versions: ["<7.0.0"]
      - dependency-type: "all"
