version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/TraxAct/src"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "Microsoft.NET.Sdk.WindowsDesktop"
        versions: ["5.0.*"]
  - package-ecosystem: "nuget"
    directory: "/TraxAct/src"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "*"
        versions: ["[!8.*]"]

on:
  workflow_dispatch:
