# This GitHub Actions workflow builds and tests the TraxAct application
# It runs on push and pull requests targeting the master branch.
# The workflow sets up the .NET environment, installs the Java Development Kit (JDK), and builds the project.

name: Build and Test  

# Target pull and push requests to master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master   

# Execute the job on a Windows runner
jobs:
  build:
    runs-on: windows-latest  

    # Checkout the repository code
    steps:
    - name: Checkout code  
      uses: actions/checkout@v4  
      
    - name: Setup .NET  
      uses: actions/setup-dotnet@v4  
      with:
        # .NET version
        dotnet-version: '7.0.x'  

    # Install the JDK
    - name: Install JDK  
      uses: actions/setup-java@v4 
      with:
        # Specify distribution and version
        distribution: 'adopt'  
        java-version: '11'     

    # Build the project and run .NET Code Analysis
    - name: Build and Run Code Analysis
      run: |
       dotnet workload install maui-android maui-windows  # Install .NET MAUI workloads for Android and Windows
       dotnet build TraxAct/TraxAct.sln --configuration Debug /p:ReportAnalyzer=true  # Build the solution with Debug configuration and run .NET Code Analysiss
      
    # Run Tests
    - name: Run Tests
      run: |
        dotnet test TraxAct/TraxActUnitTests/TraxActUnitTests.csproj --no-restore --verbosity normal

    - name: Build Docker image
      working-directory: TraxAct 
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        echo $GH_TOKEN | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker build -t traxact-app .
        docker tag traxact-app ghcr.io/${{ github.repository }}/traxact-app:latest

    # Push Docker image to registry
    - name: Push Docker image to registry
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker tag traxact-app ${{ secrets.DOCKER_USERNAME }}/traxact-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/traxact-app:latest

  deploy_to_dev:
    name: Deploy to Development
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to development environment
        run: |
          echo "Deploying to development environment..."
          # Add deployment scripts/commands here

  deploy_to_staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Deploy to staging environment
        run: |
          echo "Deploying to staging environment..."
          # Add deployment scripts/commands here

  deploy_to_prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy_to_staging
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Deploy to production environment
        run: |
          echo "Deploying to production environment..."
