name: build&test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master 

env:
  DOTNET_VERSION: '7.0.x'

jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: | 
       dotnet workload install maui-android maui-windows  # Install .NET MAUI workloads for Android and Windows
       dotnet build --configuration Release --no-restore TraxAct/src/TraxAct.csproj

    - name: Test
      run: dotnet test --no-restore --verbosity normal TraxAct/src/TraxAct.csproj
