name: Build and Deploy .NET MAUI App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.x

      - name: Install Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --configuration Release

      - name: Archive Artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.os }}
          path: |
            **/bin/Release/**/*.apk
            **/bin/Release/**/*.exe
