name: Build and Deploy .NET MAUI App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [android, windows]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.x

      - name: Install MAUI Workload
        run: dotnet workload install maui

      - name: Install Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --configuration Release

      - name: Build MAUI App
        if: matrix.os == 'android'
        run: dotnet build -t:Run -f net7.0-android

      - name: Build Windows App
        if: matrix.os == 'windows'
        run: dotnet build -t:Run -f net7.0-windows

      - name: Archive Artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.os }}
          path: |
            **/bin/Release/**/*.apk
            **/bin/Release/**/*.exe
