name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v2
      
    - name: Debug
      run: |
        pwd
        ls -la
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'

    - name: Install Android SDK and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk
        echo "y" | sdkmanager --install "platform-tools" "platforms;android-31" "build-tools;31.0.0" "extras;google;m2repository" "extras;android;m2repository"

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Debug --no-restore
    
    - name: Test
      run: dotnet test --configuration Debug --no-build --verbosity normal
