name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v2
      
    - name: Debug
      run: |
        pwd
        ls -la
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip -d "$HOME"/android-sdk
        echo 'export ANDROID_HOME="$HOME/android-sdk"' >> $HOME/.bashrc
        echo 'export PATH="$PATH:$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools"' >> $HOME/.bashrc
        source $HOME/.bashrc

     
        echo "ANDROID_HOME: $ANDROID_HOME"
        ls -la "$ANDROID_HOME"
        ls -la "$ANDROID_HOME/cmdline-tools/bin"

     
        yes | "$ANDROID_HOME/cmdline-tools/bin/sdkmanager" --licenses

        "$ANDROID_HOME/cmdline-tools/bin/sdkmanager" "platform-tools" "platforms;android-31" "build-tools;31.0.0"

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Debug --no-restore
    
    - name: Test
      run: dotnet test --configuration Debug --no-build --verbosity normal
