name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest  

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'

    - name: Install Android SDK
      run: |
        mkdir %HOMEDRIVE%%HOMEPATH%\android-sdk\cmdline-tools
        curl -o %HOMEDRIVE%%HOMEPATH%\android-sdk\cmdline-tools\commandlinetools-win-7583922_latest.zip https://dl.google.com/android/repository/commandlinetools-win-7583922_latest.zip
        tar -xf %HOMEDRIVE%%HOMEPATH%\android-sdk\cmdline-tools\commandlinetools-win-7583922_latest.zip -C %HOMEDRIVE%%HOMEPATH%\android-sdk\cmdline-tools

        echo 'export ANDROID_HOME="$HOME/android-sdk"' >> $HOME/.bashrc
        echo 'export PATH="$PATH:$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools"' >> $HOME/.bashrc
        source $HOME/.bashrc
        
        yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --licenses
        $ANDROID_HOME/cmdline-tools/bin/sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0"
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Debug --no-restore
    
    - name: Test
      run: dotnet test --configuration Debug --no-build --verbosity normal
