name: LintCheck

on:
  pull_request:
    branches:
      - master

jobs:
  format-and-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x' 

    - name: Install dotnet-format global tool
      run: dotnet tool install -g dotnet-format --version 7.0.0

    - name: Format code
      run: dotnet format --check

    - name: Install dotnet-format global tool
      run: dotnet tool install -g dotnet-format --version 7.0.0

    - name: Lint code
      run: dotnet format --lint --check

