name: PushTest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
   
        
    - name: Build
      run: |
        dotnet workload restore
        dotnet restore
        dotnet workload install maui-android maui-windows
        dotnet build --configuration Debug --no-restore

