name: PushTest

on:
  push:
    branches: 
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.407'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and test
      run: |
        dotnet build --configuration Debug
        dotnet test --configuration Debug --logger "trx;LogFileName=test_results.trx"
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true

    - name: Publish test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: '**/test_results.trx'
