name: PushTest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
        
    - name: Restore workloads
      run: |
        dotnet run project - /home/runner/work/TraxAct
        dotnet workload restore windows android tizen
        
    - name: Restore dependencies and build
      run: |
        dotnet restore
        dotnet build --configuration Debug --no-restore

