name: Routine Maintenance

on:
  schedule:
    - cron: '0 2 * * *' 
  workflow_dispatch: # Adding workflow_dispatch for on-demand trigger

jobs:
  maintenance:
    name: Perform Routine Maintenance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find Database File
        run: |
          echo "Searching for TraxActDB2.db3..."
          find . -type f -name "TraxActDB.db3" -exec ls -l {} \;

      - name: Database Backup
        run: |
          DB_PATH=$(find . -type f -name "TraxActDB2.db3" | head -n 1)
          if [ -z "$DB_PATH" ]; then
            echo "Database file not found!"
            exit 1
          fi
          mkdir -p backups
          cp "$DB_PATH" backups/database_$(date +'%Y%m%d_%H%M%S').db
   
      - name: Update Dependencies
        run: |
          dotnet restore
          dotnet nuget update -p
    
      - name: Health Check
        run: |
          DB_PATH=$(find . -type f -name "TraxActDB.db3" | head -n 1)
          if [ -z "$DB_PATH" ]; then
            echo "Database file not found!"
            exit 1
          fi
          echo "Checking SQLite database connection..."
          sqlite3 "$DB_PATH" ".tables"
        
          echo "Verifying Syncfusion Scheduler component...

      - name: Send Notification
        if: always()
        run: |
          echo "Routine maintenance completed successfully!" | mail -s "Routine Maintenance Completed" L00169798@atu.iee
