name: Routine Maintenance

on:
  schedule:
    - cron: '0 2 * * *' 
  workflow_dispatch: # Adding workflow_dispatch for on-demand trigger

jobs:
  maintenance:
    name: Perform Routine Maintenance
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Database Backup
        run: |
          $DB_PATH = "AppData\Local\Packages\3a003566-6e7e-4bd4-bac7-51a8b9009baf_9zz4h110yvjzm\LocalState\TraxActDB.db3"
          if (-not (Test-Path $DB_PATH)) {
            Write-Error "Database file not found!"
            exit 1
          }
          New-Item -ItemType Directory -Force -Path backups
          Copy-Item $DB_PATH -Destination "backups/database_$(Get-Date -Format 'yyyyMMdd_HHmmss').db"
   
      - name: Update Dependencies
        run: |
          dotnet restore
          dotnet nuget update -p
    
      - name: Health Check
        run: |
          DB_PATH=$(find . -type f -name "TraxActDB.db3" | head -n 1)
          if [ -z "$DB_PATH" ]; then
            echo "Database file not found!"
            exit 1
          fi
          echo "Checking SQLite database connection..."
          sqlite3 "$DB_PATH" ".tables"
        
          echo "Verifying Syncfusion Scheduler component...

      - name: Send Notification
        if: always()
        run: |
          echo "Routine maintenance completed successfully!" | mail -s "Routine Maintenance Completed" L00169798@atu.ie
