name: Lint Code Base
run-name: ${{ github.actor }} is linting the code 

on:
  push:
    branches-ignore: [ "master" ]
  pull_request:
    branches: [ "master" ]
  #schedule:
    #- cron: '30 21 * * 0'
  workflow_dispatch:
  
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: "master"
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
